version: '3'
    
services:
  timeseries:
    image: influxdb
    environment: 
        - INFLUXDB_DB=pairs
    ports:
        - "8086:8086"
  dashboard:
    image: grafana/grafana
    ports:
        - "3000:3000"

