version: "3"

services:
  timeseries:
    image: influxdb
    env_file:
      - ./.influx.env
    ports:
      - "8086:8086"
      - "2003:2003"
  dashboard:
    image: grafana/grafana
    ports:
      - "3000:3000"
