{
 "title": "dia/weth",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Pairs",
    "query": "SHOW TAG VALUES  WITH KEY = \"pair\""
   }
  ]
 },
 "panels": [
  {
   "title": "last Price Per WETH",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "price",
     "query": "SELECT last(\"price\") FROM \"autogen\".\"price\" WHERE (\"pair\" = 'DIA/WETH') AND $timeFilter",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=~", "value": "/^$Pairs$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "WETH" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "price",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=~", "value": "/^$Pairs$/" }
     ]
    }
   ]
  },
  {
   "title": "Highest in selected time duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "price",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=~", "value": "/^$Pairs$/" }
     ]
    }
   ]
  },
  {
   "title": "lowest in selected time duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "price",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=~", "value": "/^$Pairs$/" }
     ]
    }
   ]
  },
  {
   "title": "News",
   "type": "news",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}